### PR TITLE
Fixes #62

### LINKED ISSUE #62: AggregateRoot does not increment version when applying events
```csharp
[Test]
public void Create()
{
  var aggregate = new Aggregate();
  Assert.AreEqual(1, aggregate.Events.Count);
  Assert.AreEqual(1, aggregate.Version);
}
```

### PR DESCRIPTION
**Pull request by hellfirehd**
Increments Aggregate.Version as domain events are applied.  Does not modify IDomainEvent.

### CODE REVIEW

**Comment by lucabriguglia** [comment]
Thanks for the contribution

**Comment by hellfirehd** [comment]
When can we get a new release with this on Nuget?

**Comment by lucabriguglia** [comment]
Saturday, sorry for the delay

**Comment by lucabriguglia** [comment]
Published :-)

**Pull request merged**
